api: searching issues by phrases.
Zeal-Student-Developers/issue-tracker-mobile-client pull request #19
Opened 2021-05-10 17:50 UTC by doflamingo721

1. implemented searching issues and displaying them on search page.

2021-05-11 04:15 UTC, FaiyazMujawar requested changes
Everything looks good. Just rectify the typo. Also, a note: if the PR is about search page, you should not include something which is not related to search page. You have included changes to profile page as well. Else everything is ok.

2021-05-11 04:15 UTC, FaiyazMujawar commented on lib/src/pages/search_bar.dart
> +  Future<void> buildSearIssuePage() async {
Here's a typo!

2021-05-11 04:20 UTC, Siddharaj-Jawalkar reviewed
looks everything fine to me.

2021-05-12 05:41 UTC, doflamingo721 commented
Completed all the necessary changes

2021-05-12 05:42 UTC, merged

2021-05-12 19:23 UTC, drigio commented
Good work @doflamingo721 @FaiyazMujawar !